import { z } from 'zod'

export const syncOperationSchema = z.discriminatedUnion('type', [
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    entryId: z.uuid(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('entry.create'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    entryId: z.uuid(),
    expectedVersion: z.number().int().positive(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('entry.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    entryId: z.uuid(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('entry.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('journey.create'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('journey.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('journey.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stageId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stage.create'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stageId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stage.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stageId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stage.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stopId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stop.create'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stopId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stop.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    stopId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('stop.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    guideId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('guide.create'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    guideId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('guide.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    guideId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('guide.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    entryId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    latitude: z.number().min(-90).max(90).nullable(),
    locationTitle: z.string().max(160).nullable(),
    longitude: z.number().min(-180).max(180).nullable(),
    stageId: z.uuid().nullable(),
    status: z.enum(['pending', 'syncing', 'failed']),
    stopId: z.uuid().nullable(),
    type: z.literal('journey.assignment.upsert'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    photoId: z.uuid(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('photo.upload'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    photoId: z.uuid(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('photo.gps.update'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    entryId: z.uuid(),
    id: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    photoId: z.uuid(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('photo.delete'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    label: z.string(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    photoId: z.uuid(),
    slug: z.string(),
    status: z.enum(['pending', 'syncing', 'failed']),
    tagId: z.uuid(),
    type: z.literal('photo.tag.assign'),
  }),
  z.object({
    createdAt: z.iso.datetime({ offset: true }),
    creatorId: z.uuid(),
    id: z.uuid(),
    journeyId: z.uuid(),
    lastAttemptAt: z.iso.datetime({ offset: true }).optional(),
    photoId: z.uuid(),
    slug: z.string(),
    status: z.enum(['pending', 'syncing', 'failed']),
    type: z.literal('photo.tag.remove'),
  }),
])

export type SyncOperation = z.infer<typeof syncOperationSchema>
