// Shared with the media-upload edge function (Deno); tested here and used by
// web/app clients to build requests.
export {
  completeMultipartXml,
  DeleteMediaError,
  deleteMediaObjects,
  extensionFor,
  IMAGE_MAX_BYTES,
  IMAGE_VARIANT_KINDS,
  mediaPrefix,
  MULTIPART_PART_BYTES,
  objectKey,
  objectUrl,
  parseListPage,
  parseUploadIdXml,
  parseUploadRequest,
  partCount,
  publicUrl,
  r2Endpoint,
  VIDEO_DURATION_TOLERANCE_MS,
  VIDEO_MAX_BYTES,
  VIDEO_MAX_DURATION_MS,
  type ImageContentType,
  type ImageVariantKind,
  type ObjectStore,
  type UploadContentType,
  type UploadKind,
  type UploadRequest,
} from '../../../supabase/functions/_shared/media/upload.ts'
